### ISSUE TITLE
Поле `Дата встречи` не принимает введенного значения при реализации теста

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/AutoTestDZ_5.1_Patterns#1]
## Описание 
При вводе даты через cssSelector `[data-test-id='date'] input` в поле `Дата встречи` формы Карты с доставкой изменение даты не происходит. Выставляется автоматическая дата по правилу `+3 дня к настоящей дате`.

## Локация дефекта
В консоле браузера:
`#root > div > form > fieldset > div:nth-child(2) > span > span > span`
В коде теста:
`https://github.com/migbaranes/AutoTestDZ_5.1_Patterns/blob/c80b9a802a2a854320565216b7b82f625cee9fa1/src/test/java/ru/netology/delivery/test/DeliveryTest.java#L35`

## Шаги воспроизведения

1. открыть проект на GitHab по ссылке: `https://github.com/migbaranes/AutoTestDZ_5.1_Patterns`;
2. выполнить `git clone`;
3. запустить в терминале `java -jar app-replan-delivery.jar`;
4. запустить тест ;
5. перейти по ссылке: `http://localhost:9999/`;

***Ожидаемый результат:***
в форме дата соответствует дате в автотесте .
***Фактический результат:***
в форме дата = `+3 дня к настоящей дате` .

## Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by andrew-pahomov** [comment]
Вы забыли о необходимости очистки поля ввода даты от дефолтного значения. Рассказывал об этом на разборных вебинарах.
